name = "aiken-lang/trees"
version = "0.1.0"
licences = ["Apache-2.0"]
description = "We got trees!"

[repository]
user = "aiken-lang"
project = "trees"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "main"
source = "github"
