name = "aiken-lang/trees"
version = "0.0.1"
licences = ["Apache-2.0"]
description = "We got trees!"

dependencies = [
  { name = "aiken-lang/stdlib", version = "288d05b0d1421eafe936010ff96e885164e8a7bd", source = "github" }
]
